### ISSUE TITLE
ECONNREFUSED error for postgres

### ISSUE THREAD

**Issue by matt212** [MichalZalecki/docker-compose-node-postgres#1]
Hi, 

i am using provided docker compose file
```
version: "3"
services:
  app:
    build: ./
    depends_on:
      - postgres
    ports:
      - "3009:3009"
      - "9229:9229"
  postgres:
    image: postgres:9.6.8-alpine
    environment:
      POSTGRES_PASSWORD: postgres


```
i am getting below error any suggestion on same 

```
{ Error: connect ECONNREFUSED 127.0.0.1:5432
app_1       |        at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1083:14)
app_1       |      errno: 'ECONNREFUSED',
app_1       |      code: 'ECONNREFUSED',
app_1       |      syscall: 'connect',
app_1       |      address: '127.0.0.1',
app_1       |      port: 5432 } }
```

**Comment by MichalZalecki** [comment]
What's the log from Postgres container?

**Comment by matt212** [comment]
any ideas how to check logs from postgres container?? bit nascent in docker actually

**Comment by MichalZalecki** [comment]
```
docker-compose logs postgres
```

**Comment by matt212** [comment]
thanks give me sometime i'll revert with an update accordingly

**Comment by matt212** [comment]
hi @MichalZalecki , 
as per 
`docker-compose logs postgres`
below is output wherein database is open for connections
![Screenshot from 2019-03-14 16:20:08](https://user-images.githubusercontent.com/1698139/54351331-44bf0c80-4675-11e9-997d-c564c705343b.png)

**Comment by matt212** [comment]
hi @MichalZalecki ,
i got it working my only problem is in place of **host** everywhere 127.0.0.1 i have to use 'postgres'  in 
i wanted to know  why `postgres` in host  worked and how to configure compose file to listen to host  env variables  !
```
version: '3'
services:
 node-app:
    build: ./
    ports:
      - "3009:3009"
    depends_on:
        - redis
        - postgres
    links:
        - redis
        - postgres
    command: bash -c 'apt-get update && apt-get install -y postgresql-client && yarn createDB && yarn pgRestore && yarn test'
 redis:
        image: redis
        ports:
          - "6379"
 postgres:
        image: postgres:latest
        ports:
          - "5432"
        environment:
         POSTGRES_HOST: localhost
         POSTGRES_PASSWORD: meh980
         POSTGRES_USER: postgres
         POSTGRES_DB: postgres
          
```
